# Generated by Django 3.2.4 on 2021-06-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=400, verbose_name='description')),
                ('ingredients', models.TextField(blank=True, max_length=100, verbose_name='ingredients')),
                ('difficulty', models.TextField(verbose_name='difficulty')),
                ('favourite', models.BooleanField(default=False, verbose_name='favourite')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
            ],
        ),
    ]
