# Generated by Django 3.2.4 on 2021-06-10 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingbook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cookingbook',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='cookbooks_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
