# Generated by Django 3.2.4 on 2021-06-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=1500, verbose_name='description')),
                ('ingredients', models.TextField(blank=True, max_length=100, verbose_name='ingredients')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Intermediate'), (3, 'Hard')])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
    ]
