# Generated by Django 3.2.4 on 2021-06-10 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('cookbooks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cookbooks',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='cookbooks.CookingBook'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='recipes_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
