name: backend_motion
dependencies:
  - python=3.9
  - pip=21.1
  - psycopg2=2.8.5
  - pip:
      - django==3.2
      - djangorestframework==3.12
      - djangorestframework-simplejwt==4.7
      - gunicorn==20.1

